### ISSUE TITLE
java build failed - cannot load crux-core

### ISSUE THREAD

**Issue by KnowledgeGarden** [xtdb/xtdb-in-a-box#1]
Failed to execute goal on project cruxinabox: Could not resolve dependencies for project com.github.deobald:cruxinabox:jar:0.0.1: Failed to collect dependencies at juxt:crux-core:jar:21.02-1.15.0-beta: Failed to read artifact descriptor for juxt:crux-core:jar:21.02-1.15.0-beta: Could not transfer artifact juxt:crux-core:pom:21.02-1.15.0-beta from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [clojars (http://clojars.org/repo/, default, releases+snapshots)]

That jar is clearly online. Never seen a failure like this before.

**Comment by KnowledgeGarden** [comment]
I've moved on from this experiment, now adjusting the code to the xtdb-in-a-doc tutorial. That's got a different issue.

**Comment by deobald** [comment]
@KnowledgeGarden I think this bug still exists; I hadn't updated this repo when Crux was renamed to XTDB since I didn't think anything pointed to it. I'll try to get it resolved when I'm back at work next week anyway, so no one else runs into this problem.

In the meantime, I would suggest looking through https://xtdb.com/howto/quickstart.html

Enjoy XTDB! :)

**Comment by deobald** [comment]
These issues should all be sorted now, in addition to the peculiar MacOS + JVM16/17 snags that people sometimes stumble on. There is a completely new documentation setup coming out this week (hopefully) so I haven't linked this from the old Quickstart in the interest of avoiding collisions. This will be linked soon, though.

Moved the repo to github.com/xtdb org so I'm no longer the owner.
